server:
  port: 8010
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://119.45.145.247:8003/eureka

spring:
  application:
    name: MICROSERVICE-CODESOCKET
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  redis:
    host: 119.45.145.247
    port: 6379
    timeout: 1000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    database: 0
    password:
